name: CI
on:
  pull_request:
  push:
    branches: ["master", "staging", "trying"]

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  CI: 1
  RUST_BACKTRACE: short
  RUSTFLAGS: -D warnings
  RUSTUP_MAX_RETRIES: 10

jobs:
  test:
    name: Rust
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: Swatinem/rust-cache@6720f05bc48b77f96918929a9019fb2203ff71f8
    - run: rustup update --no-self-update stable
    - run: sudo apt-get install lua5.3
    - run: cargo test
